-- AlterTable
ALTER TABLE `users` ADD COLUMN `created_at` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `device_token` VARCHAR(255) NULL,
    ADD COLUMN `device_type` VARCHAR(255) NULL,
    ADD COLUMN `phone_no` VARCHAR(255) NULL,
    ADD COLUMN `profile_pic` VARCHAR(255) NULL,
    ADD COLUMN `remember_token` VARCHAR(255) NULL,
    ADD COLUMN `updated_at` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `email_verified_at` DATETIME(0) NULL,
    MODIFY `role_id` INTEGER NULL;
